name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # Just under 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to DIAMOND
        run: sudo hostnamectl set-hostname DIAMOND

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Restore backup files
        run: |
          if [ -f ./backup/backup.zip ]; then
            unzip -o ./backup/backup.zip -d /
          else
            echo "No backup found, starting fresh"
          fi

      - name: Create user DIAMOND with sudo
        run: |
          if ! id -u DIAMOND >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash DIAMOND
            echo "DIAMOND:DIAMOND" | sudo chpasswd
            sudo usermod -aG sudo DIAMOND
            echo "DIAMOND ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/DIAMOND
          fi

      - name: Start SSHx.io session
        run: |
          curl -sSf https://sshx.io/get | sh -s run

      - name: Sleep to keep VPS alive
        run: sleep 21000  # ~5h50m to stay under GitHub's 6h limit

      - name: Backup VPS data
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup

      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
